import { homedir } from "node:os";
export const DEFAULT_CONFIG = {
    profile: {
        profileName: "",
        displayName: "",
        language: "ko",
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
        workspace: homedir(),
    },
    ai: {
        connection: {
            provider: "",
            model: "",
        },
    },
    security: {
        allowedPaths: [],
        approvalMode: "on-miss",
        approvalTimeout: 60,
        approvalTimeoutFallback: "deny",
        allowedCommands: [],
    },
    webui: {
        enabled: true,
        port: 18888,
        host: "127.0.0.1",
        preferredUiMode: "beginner",
        admin: {
            enabled: false,
        },
        auth: {
            enabled: false,
        },
    },
    slack: {
        enabled: false,
        botToken: "",
        appToken: "",
        allowedUserIds: [],
        allowedChannelIds: [],
    },
    discord: {
        enabled: false,
        botToken: "",
        applicationId: "",
        publicKey: "",
        allowedUserIds: [],
        allowedGuildIds: [],
        allowedChannelIds: [],
        grantedIntents: [],
        botPermissions: [],
        installedGuildIds: [],
        largeGuildMode: false,
    },
    googleChat: {
        enabled: false,
        projectId: "",
        appCredentialJson: "",
        serviceAccountEmail: "",
        webhookUrl: "",
        verificationToken: "",
        allowedUserIds: [],
        allowedSpaceIds: [],
        deployedSpaceIds: [],
        grantedScopes: [],
        appPublished: false,
        domainWideDelegation: false,
    },
    imessage: {
        enabled: false,
        mode: "manual_confirm",
        localBridgeEnabled: false,
        yeonjangBridgeEnabled: false,
        riskAcknowledged: false,
        messagesAppAvailable: false,
        userSessionActive: false,
        automationPermissionGranted: false,
        allowedRecipientIds: [],
        manualConfirmationRequired: true,
    },
    kakaoTalk: {
        enabled: false,
        mode: "local_bridge",
        businessApiEnabled: false,
        businessApiKey: "",
        channelId: "",
        localBridgeEnabled: false,
        yeonjangBridgeEnabled: false,
        riskAcknowledged: false,
        kakaoTalkAppAvailable: false,
        userSessionActive: false,
        automationPermissionGranted: false,
        allowedUserIds: [],
        allowedRoomIds: [],
        manualConfirmationRequired: true,
        rateLimitPerMinute: 6,
    },
    scheduler: {
        enabled: true,
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    },
    mqtt: {
        enabled: false,
        host: "0.0.0.0",
        port: 1883,
        username: "",
        password: "",
        allowAnonymous: false,
    },
    search: {
        web: {
            provider: "duckduckgo",
            maxResults: 5,
        },
    },
    memory: {
        compaction: {
            minContextTokens: 3000,
        },
        sessionRetentionDays: 30,
    },
    orchestration: {
        maxDelegationTurns: 0,
        mode: "single_nobie",
        featureFlagEnabled: false,
        subAgents: [],
        teams: [],
    },
    mcp: {
        servers: {},
    },
    skills: {
        items: [],
    },
};
//# sourceMappingURL=types.js.map