import { ENTERPRISE_TOPOLOGY_SCHEMA_VERSION, } from "../contracts/enterprise-topology.js";
export function buildExampleEnterpriseTopology(now = Date.UTC(2026, 3, 29, 0, 0, 0)) {
    return {
        schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
        entityType: "topology",
        id: "topology:customer-success",
        name: "Customer Success Topology",
        description: "Minimal reusable Enterprise Topology fixture for validator, compiler, and runtime tests.",
        status: "draft",
        createdAt: now,
        updatedAt: now,
        nodes: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "node",
                id: "node:intake",
                name: "Customer Request Intake",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                nodeType: "function",
                owner: { entityType: "position", id: "position:cs-lead" },
                tags: ["customer-success", "intake"],
                children: ["node:triage"],
                template: {
                    templateId: "template:generic-work-node",
                    source: "system_preset",
                    fixedRoleCatalog: false,
                },
                allowedToolIds: ["tool:crm-search"],
                allowedSystemIds: ["system:crm"],
                failurePolicy: {
                    failureReportRequired: true,
                    allowPartialSuccess: true,
                    fallbackNodeIds: ["node:triage"],
                },
                recoveryPolicy: {
                    retryAllowed: true,
                    redelegationAllowed: true,
                    fallbackAllowed: true,
                    partialSuccessAllowed: true,
                },
            },
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "node",
                id: "node:triage",
                name: "Customer Request Triage",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                nodeType: "review_node",
                tags: ["customer-success", "triage"],
                children: [],
                allowedToolIds: [],
                allowedSystemIds: [],
                failurePolicy: {
                    failureReportRequired: true,
                    allowPartialSuccess: true,
                    fallbackNodeIds: [],
                },
                recoveryPolicy: {
                    retryAllowed: false,
                    redelegationAllowed: false,
                    fallbackAllowed: false,
                    partialSuccessAllowed: true,
                },
            },
        ],
        teams: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "team",
                id: "team:customer-success-coverage",
                name: "Customer Success Coverage Team",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                purpose: "Logical grouping for customer success topology coverage.",
                nodeIds: ["node:intake", "node:triage"],
                tags: ["coverage"],
            },
        ],
        orgUnits: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "org_unit",
                id: "org:customer-success",
                name: "Customer Success",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                positionIds: ["position:cs-lead"],
                personIds: ["person:lee"],
                kpiIds: ["kpi:first-response-time"],
                responsibilityArea: "Customer response operations.",
            },
        ],
        positions: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "position",
                id: "position:cs-lead",
                name: "Customer Success Lead",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                orgUnitId: "org:customer-success",
                personIds: ["person:lee"],
                responsibilityIds: ["resp:intake-owner", "resp:triage-owner"],
            },
        ],
        persons: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "person",
                id: "person:lee",
                name: "Lee",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                positionIds: ["position:cs-lead"],
                orgUnitIds: ["org:customer-success"],
                availability: "available",
            },
        ],
        memberships: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "membership",
                id: "membership:lee-cs-lead",
                name: "Lee as Customer Success Lead",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                personId: "person:lee",
                positionId: "position:cs-lead",
                orgUnitId: "org:customer-success",
            },
        ],
        authorityRules: [],
        responsibilities: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "responsibility_matrix_entry",
                id: "resp:intake-owner",
                name: "Customer Request Intake Responsibility",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                scope: { entityType: "node", id: "node:intake" },
                responsible: { entityType: "position", id: "position:cs-lead" },
                accountable: { entityType: "position", id: "position:cs-lead" },
                consulted: [],
                informed: [],
            },
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "responsibility_matrix_entry",
                id: "resp:triage-owner",
                name: "Customer Request Triage Responsibility",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                scope: { entityType: "node", id: "node:triage" },
                responsible: { entityType: "position", id: "position:cs-lead" },
                accountable: { entityType: "position", id: "position:cs-lead" },
                consulted: [],
                informed: [],
            },
        ],
        systems: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "enterprise_system",
                id: "system:crm",
                name: "CRM",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                systemType: "internal",
                dataDomainIds: ["data:customer"],
                criticality: "high",
            },
        ],
        tools: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "enterprise_tool",
                id: "tool:crm-search",
                name: "CRM Search",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                toolType: "read_only",
                systemId: "system:crm",
            },
        ],
        processes: [],
        relations: [
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "relation",
                id: "relation:intake-triage",
                name: "Intake delegates to triage",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                relationType: "delegates_to",
                from: { entityType: "node", id: "node:intake" },
                to: { entityType: "node", id: "node:triage" },
            },
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "relation",
                id: "relation:intake-crm",
                name: "Intake uses CRM",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                relationType: "uses_system",
                from: { entityType: "node", id: "node:intake" },
                to: { entityType: "enterprise_system", id: "system:crm" },
            },
            {
                schemaVersion: ENTERPRISE_TOPOLOGY_SCHEMA_VERSION,
                entityType: "relation",
                id: "relation:intake-crm-search",
                name: "Intake uses CRM Search",
                status: "draft",
                createdAt: now,
                updatedAt: now,
                relationType: "uses_tool",
                from: { entityType: "node", id: "node:intake" },
                to: { entityType: "enterprise_tool", id: "tool:crm-search" },
            },
        ],
    };
}
//# sourceMappingURL=examples.js.map